// Core domain types for TicketFlow
// These mirror the Supabase schema exactly so TypeScript catches mismatches early.

export type TicketStatus = "Open" | "In Progress" | "Closed";
export type TicketPriority = "Low" | "Medium" | "High" | "Urgent";

export interface Ticket {
  id: string;                  // uuid — internal Supabase PK
  ticket_id: string;           // human-readable e.g. "TKT-001" — generated by DB trigger
  customer_name: string;
  customer_email: string;
  subject: string;
  description: string;
  status: TicketStatus;
  priority: TicketPriority;
  ai_summary: string | null;   // null when AI call failed or hasn't run yet
  created_at: string;          // ISO-8601 timestamp
  updated_at: string;
}

export interface Note {
  id: string;           // uuid
  ticket_id: string;    // uuid FK → tickets.id
  note_text: string;
  created_at: string;
}

// Ticket with its notes joined — returned by GET /api/tickets/[ticket_id]
export interface TicketWithNotes extends Ticket {
  notes: Note[];
}

// Analytics payload — returned by GET /api/analytics
export interface AnalyticsData {
  total: number;
  open: number;
  inProgress: number;
  closed: number;
  dailyCounts: { date: string; count: number }[];  // last 7 days
}
